package entity

const entityTpl = `
// Code generated by protoc-gen-uwgo-entity. DO NOT EDIT.
// source: {{ .File.Name }}

package {{ package .File }}

{{ range .Entities }}

// GetEntityIdentifier returns the value from the field marked as the identifier
func (m *{{ .Msg.Name }}) GetEntityIdentifier() {{ entityReturnType .Entity }} {
	if m != nil {
		return m.{{ .Entity.Name.UpperCamelCase }}
	}
	return {{ entityDefaultReturn .Entity }}
}

{{ end }}
`
